#! /bin/sh
gcc -o heap_test -g $1 Db/dbmem.c Db/dballoc.c Db/dbdata.c Db/dblock.c Db/dbindex.c Db/dblog.c Db/dbhash.c Db/dbcompare.c Db/dbquery.c Db/dbutil.c Db/dbmpool.c Db/dbschema.c dbmalloc.c -lm
