#! /bin/sh
gcc -o heap_test -g $1 db/dbmem.c db/dballoc.c db/dbdata.c db/dblock.c db/dbindex.c db/dblog.c db/dbhash.c db/dbcompare.c db/dbquery.c db/dbutil.c db/dbmpool.c db/dbschema.c db/dbmalloc.c -lm
